17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Models/ErrorViewModel.cs
using System;

namespace PersonsAndAwardsMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Models/PersonAndAwardsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Entities;

namespace PersonsAndAwardsMVC.Models
{
    public class PersonAndAwardsViewModel
    {
        public Person person { get; set; }
        public IEnumerable<Award> allAvailableAwards { get; set; }

        public PersonAndAwardsViewModel()
        {
            person = new Person();
            allAvailableAwards = new List<Award>();
        }
        public PersonAndAwardsViewModel(IEnumerable<Award> allAvailableAwards)
        {
            person = new Person();
            this.allAvailableAwards = allAvailableAwards;
        }
        public PersonAndAwardsViewModel(Person person, IEnumerable<Award> allAvailableAwards) : this(allAvailableAwards)
        {
            this.person = person;
        }
    }
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Controllers/AwardsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;

using PersonsAndAwardsMVC.Models;
using Entities;

namespace PersonsAndAwardsMVC.Controllers
{
    public class AwardsController : Controller
    {
        private readonly IMySingletonService singletonService;

        public AwardsController(IMySingletonService singletonService)
        {
            this.singletonService = singletonService;
        }

        public IActionResult Awards()
        {
            return View(singletonService.AwardBL.GetList());
        }
        public IActionResult AddAwardForm()
        {
            return View(new Award());
        }
        [HttpPost]
        public IActionResult AddAwardForm(Award model)
        {
            if (!ModelState.IsValid) { return View(); }

            singletonService.AwardBL.Add(model);
            return RedirectToAction("Awards");
        }
        public IActionResult EditAwardForm(int id)
        {
            return View(singletonService.AwardBL.GetListItem(id));
        }
        [HttpPost]
        public IActionResult EditAwardForm(Award model)
        {
            if (!ModelState.IsValid) { return View(); }

            singletonService.AwardBL.SetData(model.ID, model.GetData());
            return RedirectToAction("Awards");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Controllers/CommonController.cs
using Microsoft.AspNetCore.Mvc;
using PersonsAndAwardsMVC.Models;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;

namespace PersonsAndAwardsMVC.Controllers
{
    public class CommonController : Controller
    {
        private readonly IMySingletonService singletonService;

        public CommonController(IMySingletonService singletonService)
        {
            this.singletonService = singletonService;
        }

        public IActionResult RemoveConfirmationForm(string type, int id)
        {
            ViewData["type"] = type;
            ViewData["id"] = id;

            return View();
        }
        public IActionResult RemoveConfirmed(string type, int id)
        {
            if (type == "person")
            {
                singletonService.PersonBL.Remove(id);

                return RedirectToAction("Persons", "Persons");
            }
            if (type == "award")
            {
                foreach (var person in singletonService.PersonBL.GetList())
                {
                    singletonService.PersonBL.RemoveAward(person.ID, id);
                }
                singletonService.AwardBL.Remove(id);

                return RedirectToAction("Awards", "Awards");
            }

            return View(new ErrorViewModel());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;

using PersonsAndAwardsMVC.Models;
using Entities;

namespace PersonsAndAwardsMVC.Controllers
{
    public class PersonsController : Controller
    {
        private readonly IMySingletonService singletonService;

        public PersonsController(IMySingletonService singletonService)
        {
            this.singletonService = singletonService;
        }

        public IActionResult Persons()
        {
            return View(singletonService.PersonBL.GetList());
        }
        public IActionResult AddPersonForm()
        {
            return View(new PersonAndAwardsViewModel(
                singletonService.AwardBL.GetList()));
        }
        [HttpPost]
        public IActionResult AddPersonForm(PersonAndAwardsViewModel model, List<int> choosedAwards)
        {
            if (!ModelState.IsValid) { return View(new PersonAndAwardsViewModel(model.person, singletonService.AwardBL.GetList())); }

            int personID = singletonService.PersonBL.Add(model.person);
            foreach (int awardID in choosedAwards)
            {
                singletonService.PersonBL.AddAward(
                    personID,
                    singletonService.AwardBL.GetListItem(awardID));
            }

            return RedirectToAction("Persons");
        }
        public IActionResult EditPersonForm(int id)
        {
            return View(new PersonAndAwardsViewModel(
                singletonService.PersonBL.GetListItem(id),
                singletonService.AwardBL.GetList()));
        }
        [HttpPost]
        public IActionResult EditPersonForm(PersonAndAwardsViewModel model, List<int> choosedAwards)
        {
            if (!ModelState.IsValid) { return View(new PersonAndAwardsViewModel(model.person, singletonService.AwardBL.GetList())); }

            singletonService.PersonBL.SetData(model.person.ID, model.person.GetData());
            singletonService.PersonBL.ResetAwards(model.person.ID);
            foreach (int awardID in choosedAwards)
            {
                singletonService.PersonBL.AddAward(
                    model.person.ID,
                    singletonService.AwardBL.GetListItem(awardID));
            }

            return RedirectToAction("Persons");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Awards/AddAwardForm.cshtml
@model Entities.Award

@{
    ViewData["Title"] = "Add/Edit Award";
}

@using (Html.BeginForm("AddAwardForm", "Awards", FormMethod.Post))
{
    @Html.ValidationSummary(true)

<div class="container">

    <h2>Add New Award</h2>

    <table class="inputs-table">
        <tr>
            <td><label for="title">Title:</label></td>
            <td>
                <input asp-for="Title" type="text" 
                       size="31" 
                       placeholder="Max: 50 symbols" />
                <span asp-validation-for="Title"></span>
            </td>
        </tr>
        <tr>
            <td><label for="description">Description: </label></td>
            <td>
                <textarea asp-for="Description" 
                          size="31" 
                          cols="30" 
                          rows="10" 
                          placeholder="Max: 250 symbols" 
                          style="resize: none;"></textarea>
                <span asp-validation-for="Description"></span>
            </td>
        </tr>
    </table>

    <input type="submit" value="Confirm" />

</div>
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Awards/Awards.cshtml
@model IEnumerable<Entities.Award>

@{
    ViewData["Title"] = "Awards";
}

<div class="container">
    <nav class="navbar-table_actions">
        <ul class="navbar-table_actions-nav">
            <li class="nav-item">
                <a class="nav-link" 
                   asp-controller="Awards" 
                   asp-action="AddAwardForm">
                   Add New Award
                </a>
            </li>
        </ul>

        <hr>
    </nav>

    <table class="table">
        <tr class="table-header">
            <th class="table_header-operation">Operation</th>
            <th class="table_header-id">ID</th>
            <th class="table_header-title">Title</th>
            <th class="table_header-description">Description</th>
        </tr>

        @foreach (var award in Model)
        {
            <tr>
                <td class="table_header-operation">
                    <a class="table-link"
                       asp-controller="Awards"
                       asp-action="EditAwardForm"
                       asp-route-id="@award.ID">
                       Edit
                    </a> |
                    <a class="table-link"
                       asp-controller="Common"
                       asp-action="RemoveConfirmationForm"
                       asp-route-type="award"
                       asp-route-id="@award.ID">
                       Remove
                    </a>
                </td>
                <td class="table_header-id">@award.ID</td>
                <td class="table_header-title">@award.Title</td>
                <td class="table_header-description">@award.Description</td>
            </tr>
        }
    </table>
</div>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Awards/EditAwardForm.cshtml
@model Entities.Award

@{
    ViewData["Title"] = "Add/Edit Award";
}

@using (Html.BeginForm("EditAwardForm", "Awards", FormMethod.Post))
{
    @Html.ValidationSummary(true)

<div class="container">

    <h2>Add New Award</h2>

    <input asp-for="ID" type="hidden" />

    <table class="inputs-table">
        <tr>
            <td><label for="title">Title:</label></td>
            <td>
                <input asp-for="Title" type="text"
                       size="31"
                       placeholder="Max: 50 symbols" />
                <span asp-validation-for="Title"></span>
            </td>
        </tr>
        <tr>
            <td><label for="description">Description: </label></td>
            <td>
                <textarea asp-for="Description"
                          size="31"
                          cols="30"
                          rows="10"
                          placeholder="Max: 250 symbols"
                          style="resize: none;"></textarea>
                <span asp-validation-for="Description"></span>
            </td>
        </tr>
    </table>

    <input type="submit" value="Confirm" />

</div>
}

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Common/RemoveConfirmationForm.cshtml
@{
    ViewData["Title"] = "Remove selected item";
    string type = ViewData["type"] as string;
    int id = Convert.ToInt32(ViewData["id"]);
}

<div class="container">

    <h2>Remove selected item?</h2>

    <button class="button-submit"
            onclick="location.href='@Url.Action("RemoveConfirmed", "Common", new {type = type, id=id}, null)'">
        Submit Changes
    </button>

</div>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Home/Awards.cshtml
@model IEnumerable<AwardViewModel>

@{
    ViewData["Title"] = "Awards";
}

<div class="container">
    <nav class="navbar-table_actions">
        <ul class="navbar-table_actions-nav">
            <li class="nav-item">
                <a class="nav-link" 
                   asp-area="" 
                   asp-controller="Home" 
                   asp-action="AwardForm"
                   asp-route-task="add"
                   asp-route-id="">Add New Award</a>
            </li>
        </ul>

        <hr>
    </nav>

    <table class="table">
        <tr class="table-header">
            <th class="table_header-operation">Operation</th>
            <th class="table_header-id">ID</th>
            <th class="table_header-title">Title</th>
            <th class="table_header-description">Description</th>
        </tr>

        @foreach (var award in Model)
        {
            <tr>
                <td class="table_header-operation">
                    <a class="table-link"
                       asp-controller="Home"
                       asp-action="AwardForm"
                       asp-route-task="edit"
                       asp-route-id="@award.ID">
                       Edit
                    </a> |
                    <a class="table-link"
                       asp-controller="Home"
                       asp-action="RemoveConfirmationForm"
                       asp-route-type="award"
                       asp-route-id="@award.ID">
                       Remove
                    </a>
                </td>
                <td class="table_header-id">@award.ID</td>
                <td class="table_header-title">@award.Title</td>
                <td class="table_header-description">@award.Description</td>
            </tr>
        }
    </table>
</div>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Home/PersonForm.cshtml
@model PersonsAndAwardsMVC.Models.PersonViewModel
@{
    ViewData["Title"] = "Add/Edit Person";
    IEnumerable<Entities.Award> allAvailableAwards = ViewData["AllAvailableAwards"] as IEnumerable<Entities.Award>;
    string task = ViewData["task"] as string;
}

@using (Html.BeginForm("PersonForm", "Home", new { task = task }, FormMethod.Post))
{
    @*@Html.ValidationSummary(true)*@

<div class="container">

    @if (task == "add")
    {
        <h2>Add New Person</h2>
    }
    @if (task == "edit")
    {
        <h2>Edit Selected Person</h2>
    }

    <table class="inputs-table">
        <tr>
            <td><label for="Name">Name:</label></td>
            <td>
                <input type="text"
                       name="Name"
                       id="Name"
                       maxlength="50"
                       size="43"
                       value="@Model.Name">
            </td>
        </tr>

        <tr>
            <td><label for="LastName">LastName:</label></td>
            <td>
                <input type="text"
                       name="LastName"
                       id="LastName"
                       maxlength="50"
                       size="43"
                       value="@Model.LastName">
            </td>
        </tr>

        <tr>
            <td><label for="Birthdate">Birthdate:</label></td>
            <td>
                <input type="date"
                       name="Birthdate"
                       id="Birthdate"
                       min="@DateTime.Now.AddYears(-150).ToString("yyyy-MM-dd")"
                       max="@DateTime.Now.ToString("yyyy-MM-dd")"
                       value="@Model.Birthdate.ToString("yyyy-MM-dd")"
                       style="width: 320px;">
            </td>
        </tr>

        <tr>
            <td><label for="allAvailableAwards">Awards:</label></td>
            <td>
                <table class="inputs-table_inner">
                    <tr>
                        <td rowspan="2">
                            <select name="allAvailableAwards"
                                    id="allAvailableAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in allAvailableAwards)
                                    {
                                        if (!Model.Awards.Contains(award)) { <option value="@award.ID">@award.Title</option> }
                                    }
                            </select>
                        </td>

                        <td><input type="button" name="removeAward" id="removeAward" value="<"></td>

                        <td rowspan="2">
                            <select name="choosedAwards"
                                    id="choosedAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in Model.Awards)
                                    {
                                        <option value="@award.ID" selected>@award.Title</option>
                                    }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="button" name="addAward" id="addAward" value=">"/>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <input type="submit" name="submit" id="submit" value="Confirm" />

</div>
}

<script>
    $(document).ready(function ()
    {
        $('#submit').click(function ()
        {
            $('#choosedAwards option').prop('selected', true);
        });

        $('#addAward').click(function ()
        {
            var itemID = parseInt($('#allAvailableAwards option:selected').val());
            $('#allAvailableAwards option:selected').remove().appendTo('#choosedAwards');

            console.log("Added award with ID: " + itemID);
        });

        $('#removeAward').click(function ()
        {
            var itemID = parseInt($('#choosedAwards option:selected').val());
            $('#choosedAwards option:selected').remove().appendTo('#allAvailableAwards');

            console.log("Removed award with ID: " + itemID);
        });
    });
</script>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Home/Persons.cshtml
@model IEnumerable<PersonViewModel>

@{
    ViewData["Title"] = "Persons";
}

<div class="container">
    <nav class="navbar-table_actions">
        <ul class="navbar-table_actions-nav">
            <li class="nav-item">
                <a class="nav-link" 
                   asp-area="" 
                   asp-controller="Home" 
                   asp-action="PersonForm"
                   asp-route-task="add"
                   asp-route-id="">Add New Person</a>
            </li>
        </ul>

        <hr>
    </nav>

    <table class="table">
        <tr class="table-header">
            <th class="table_header-operation">Operation</th>
            <th class="table_header-id">ID</th>
            <th class="table_header-name">Name</th>
            <th class="table_header-lastname">LastName</th>
            <th class="table_header-birthdate">Birthdate</th>
            <th class="table_header-age">Age</th>
            <th class="table_header-awards">Awards</th>
        </tr>

       @foreach (var person in Model)
        {
            <tr id="@person.ID">
                <td class="table_header-operation">
                    <a class="table-link" 
                       asp-controller="Home" 
                       asp-action="PersonForm"
                       asp-route-task="edit"
                       asp-route-id="@person.ID">
                       Edit
                    </a> |
                    <a class="table-link" 
                       asp-controller="Home" 
                       asp-action="RemoveConfirmationForm"
                       asp-route-type="person"
                       asp-route-id="@person.ID">
                       Remove
                    </a>
                </td>
                <td class="table_header-id">@person.ID</td>
                <td class="table_header-name">@person.Name</td>
                <td class="table_header-lastname">@person.LastName</td>
                <td class="table_header-birthdate">@person.Birthdate</td>
                <td class="table_header-age">@person.Age</td>
                <td class="table_header-awards">
                    @person.GetAwards()
                </td>
            </tr>
        }
    </table>
</div>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Home/RemoveConfirmationForm.cshtml
@{
    ViewData["Title"] = "Remove selected item";
    string type = ViewData["type"] as string;
    int id = Convert.ToInt32(ViewData["id"]);
}

<div class="container">

    <h2>Remove selected item?</h2>

    <button class="button-submit"
            onclick="location.href='@Url.Action("RemoveConfirmed", "Home", new {type = type, id=id}, null)'">
        Submit Changes
    </button>

</div>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Persons/AddPersonForm.cshtml
@model PersonsAndAwardsMVC.Models.PersonAndAwardsViewModel

@{
    ViewData["Title"] = "Add/Edit Person";
}

@using (Html.BeginForm("AddPersonForm", "Persons", FormMethod.Post))
{
    @Html.ValidationSummary(true)

<div class="container">

    <h2>Add New Person</h2>

    <table class="inputs-table">
        <tr>
            <td><label for="Name">Name:</label></td>
            <td>
                <input asp-for="person.Name" type="text" 
                        size="43" 
                        placeholder="Max: 50 symbols"/>
                <span asp-validation-for="person.Name"></span>
            </td>
        </tr>

        <tr>
            <td><label for="LastName">LastName:</label></td>
            <td>
                <input asp-for="person.LastName" type="text"
                        size="43" 
                        placeholder="Max: 50 symbols"/>
                <span asp-validation-for="person.LastName"></span>
            </td>
        </tr>

        <tr>
            <td><label for="Birthdate">Birthdate:</label></td>
            <td>
                <input asp-for="person.Birthdate" type="date" style="width: 320px;" />
                <span asp-validation-for="person.Birthdate"></span>
            </td>
        </tr>

        <tr>
            <td><label for="allAvailableAwards">Awards:</label></td>
            <td>
                <table class="inputs-table_inner">
                    <tr>
                        <td rowspan="2">
                            <select name="allAvailableAwards"
                                    id="allAvailableAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in Model.allAvailableAwards)
                                    {
                                        if (!Model.person.Awards.Contains(award)) { <option value="@award.ID">@award.Title</option> }
                                    }
                            </select>
                        </td>

                        <td><input type="button" name="removeAward" id="removeAward" value="<"></td>

                        <td rowspan="2">
                            <select name="choosedAwards"
                                    id="choosedAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in Model.person.Awards)
                                    {
                                        <option value="@award.ID" selected>@award.Title</option>
                                    }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="button" name="addAward" id="addAward" value=">" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <input type="submit" name="submit" id="submit" value="Confirm" />

</div>
}

<script>
    $(document).ready(function () {
        $('#submit').click(function () {
            $('#choosedAwards option').prop('selected', true);
        });

        $('#addAward').click(function () {
            var itemID = parseInt($('#allAvailableAwards option:selected').val());
            $('#allAvailableAwards option:selected').remove().appendTo('#choosedAwards');

            console.log("Added award with ID: " + itemID);
        });

        $('#removeAward').click(function () {
            var itemID = parseInt($('#choosedAwards option:selected').val());
            $('#choosedAwards option:selected').remove().appendTo('#allAvailableAwards');

            console.log("Removed award with ID: " + itemID);
        });
    });
</script>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Persons/EditPersonForm.cshtml
@model PersonsAndAwardsMVC.Models.PersonAndAwardsViewModel

@{
    ViewData["Title"] = "Add/Edit Person";
}

@using (Html.BeginForm("EditPersonForm", "Persons", FormMethod.Post))
{
    @Html.ValidationSummary(true)

<div class="container">

    <h2>Edit Selected Person</h2>

    <input asp-for="person.ID" type="hidden" />

    <table class="inputs-table">
        <tr>
            <td><label for="Name">Name:</label></td>
            <td>
                <input asp-for="person.Name" type="text"
                       size="43"
                       placeholder="Max: 50 symbols" />
                <span asp-validation-for="person.Name"></span>
            </td>
        </tr>

        <tr>
            <td><label for="LastName">LastName:</label></td>
            <td>
                <input asp-for="person.LastName" type="text"
                       size="43"
                       placeholder="Max: 50 symbols" />
                <span asp-validation-for="person.LastName"></span>
            </td>
        </tr>

        <tr>
            <td><label for="Birthdate">Birthdate:</label></td>
            <td>
                <input asp-for="person.Birthdate" type="date" style="width: 320px;" />
                <span asp-validation-for="person.Birthdate"></span>
            </td>
        </tr>

        <tr>
            <td><label for="allAvailableAwards">Awards:</label></td>
            <td>
                <table class="inputs-table_inner">
                    <tr>
                        <td rowspan="2">
                            <select name="allAvailableAwards"
                                    id="allAvailableAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in Model.allAvailableAwards)
                                    {
                                        if (!Model.person.Awards.Contains(award)) { <option value="@award.ID">@award.Title</option> }
                                    }
                            </select>
                        </td>

                        <td><input type="button" name="removeAward" id="removeAward" value="<"></td>

                        <td rowspan="2">
                            <select name="choosedAwards"
                                    id="choosedAwards"
                                    size="5"
                                    multiple>
                                    @foreach (var award in Model.person.Awards)
                                    {
                                        <option value="@award.ID" selected>@award.Title</option>
                                    }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="button" name="addAward" id="addAward" value=">" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <input type="submit" name="submit" id="submit" value="Confirm" />

</div>
}

<script>
    $(document).ready(function ()
    {
        $('#submit').click(function ()
        {
            $('#choosedAwards option').prop('selected', true);
        });

        $('#addAward').click(function ()
        {
            var itemID = parseInt($('#allAvailableAwards option:selected').val());
            $('#allAvailableAwards option:selected').remove().appendTo('#choosedAwards');

            console.log("Added award with ID: " + itemID);
        });

        $('#removeAward').click(function ()
        {
            var itemID = parseInt($('#choosedAwards option:selected').val());
            $('#choosedAwards option:selected').remove().appendTo('#allAvailableAwards');

            console.log("Removed award with ID: " + itemID);
        });
    });
</script>

17-asp-net-basics/net/PersonsAndAwardsMVC/PersonsAndAwardsMVC/Views/Persons/Persons.cshtml
@model IEnumerable<Entities.Person>

@{
    ViewData["Title"] = "Persons";
}

<div class="container">
    <nav class="navbar-table_actions">
        <ul class="navbar-table_actions-nav">
            <li class="nav-item">
                <a class="nav-link" 
                   asp-controller="Persons" 
                   asp-action="AddPersonForm">
                   Add New Person
                </a>
            </li>
        </ul>

        <hr>
    </nav>

    <table class="table">
        <tr class="table-header">
            <th class="table_header-operation">Operation</th>
            <th class="table_header-id">ID</th>
            <th class="table_header-name">Name</th>
            <th class="table_header-lastname">LastName</th>
            <th class="table_header-birthdate">Birthdate</th>
            <th class="table_header-age">Age</th>
            <th class="table_header-awards">Awards</th>
        </tr>

       @foreach (var person in Model)
        {
            <tr id="@person.ID">
                <td class="table_header-operation">
                    <a class="table-link" 
                       asp-controller="Persons" 
                       asp-action="EditPersonForm"
                       asp-route-id="@person.ID">
                       Edit
                    </a> |
                    <a class="table-link" 
                       asp-controller="Common" 
                       asp-action="RemoveConfirmationForm"
                       asp-route-type="person"
                       asp-route-id="@person.ID">
                       Remove
                    </a>
                </td>
                <td class="table_header-id">@person.ID</td>
                <td class="table_header-name">@person.Name</td>
                <td class="table_header-lastname">@person.LastName</td>
                <td class="table_header-birthdate">@person.Birthdate</td>
                <td class="table_header-age">@person.Age</td>
                <td class="table_header-awards">
                    @string.Join(", ", person.GetAwards());
                </td>
            </tr>
        }
    </table>
</div>